# docker-compose.yml
version: "3"
services:
  app:
    build: .
    container_name: flexbox
    restart: always
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - "3333:3333"
      - "9229:9229"
    networks:
      - default

networks:
  default:
    driver: bridge